### Задача: Алгоритм Флойда–Форшала

#### Граф (з картинки):

Вершини: {1, 2, 3, 4, 5, 6}  
Ребра з вагами:  
- (1,3) = 4  
- (3,6) = 4  
- (1,6) = 1  
- (1,5) = 11  
- (5,6) = 3  
- (1,2) = 8  
- (2,3) = 5  
- (2,4) = 5  
- (4,5) = 3

---

#### Код для знаходження найкоротших шляхів методом Флойда–Форшала

In [1]:
import numpy as np

# Вершини з 1 по 6, індексація з 0 для зручності
n = 6
INF = 10**9

# Матриця ваг ребер (спочатку заповнена INF)
dist = np.full((n, n), INF)

# Відстань від вершини до самої себе 0
for i in range(n):
    dist[i][i] = 0

# Заповнюємо ваги ребер згідно з графом (індексація з 0)
edges = [
    (0, 2, 4),
    (2, 5, 4),
    (0, 5, 1),
    (0, 4, 11),
    (4, 5, 3),
    (0, 1, 8),
    (1, 2, 5),
    (1, 3, 5),
    (3, 4, 3)
]

for u, v, w in edges:
    dist[u][v] = w

# Алгоритм Флойда–Форшала
for k in range(n):
    for i in range(n):
        for j in range(n):
            if dist[i][j] > dist[i][k] + dist[k][j]:
                dist[i][j] = dist[i][k] + dist[k][j]

print("Матриця найкоротших відстаней між усіма вершинами:")
print(dist)

Матриця найкоротших відстаней між усіма вершинами:
[[         0          8          4         13         11          1]
 [1000000000          0          5          5          8          9]
 [1000000000 1000000000          0 1000000000 1000000000          4]
 [1000000000 1000000000 1000000000          0          3          6]
 [1000000000 1000000000 1000000000 1000000000          0          3]
 [1000000000 1000000000 1000000000 1000000000 1000000000          0]]


### Контрольні питання

1. **Що таке граф і які головні складові його структури?**  
   Граф — це множина вершин і ребер між ними. Основні складові: вершини (ноді), ребра (зв’язки), орієнтованість (або ні), ваги ребер (опційно).

2. **Які алгоритми використовуються для пошуку найкоротших шляхів у графах?**  
   - Алгоритм Дейкстри  
   - Алгоритм Беллмана–Форда  
   - Алгоритм Флойда–Форшала  
   - Алгоритми пошуку в ширину (для графів без ваг)  
   - Алгоритми А* і інші евристичні

3. **Як працює алгоритм Дейкстри і які його особливості?**  
   Алгоритм Дейкстри шукає найкоротший шлях від однієї вершини до всіх інших у графі з невід’ємними вагами ребер, використовуючи жадібний підхід і пріоритетну чергу. Не працює з від’ємними вагами.

4. **Що таке алгоритм Белмена–Форда і коли його варто застосовувати?**  
   Це алгоритм пошуку найкоротших шляхів з однієї вершини, який працює і з від’ємними вагами ребер, і виявляє негативні цикли. Його варто застосовувати, коли є від’ємні ваги.

5. **Як працює алгоритм Флойда–Форшала і які його переваги та недоліки?**  
   Алгоритм Флойда–Форшала знаходить найкоротші шляхи між усіма парами вершин, використовуючи динамічне програмування. Перевага — універсальність для орієнтованих графів з від’ємними вагами (без циклів з від’ємною сумою). Недолік — висока складність \(O(n^3)\), тому він не підходить для дуже великих графів.